version: "3"
networks:
  front:
    name: front
    driver: bridge

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8080:80
    networks:
      - front
