version: "3"
networks:
  front:
    name: front
    driver: bridge

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - frontend-middleware:./dist
    networks:
      - front
  nginx:
    container_name: proxy-frontend-nginx
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html/:ro
    depends_on:
      - frontend
    networks:
      - front
volumes:
  frontend-middleware:
    name: bushfrontend_frontend-middleware
