version: "3.3"
networks:
  front:
    driver: bridge

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8080:8080
    networks:
      - front
