version: "3"
networks:
  front:
    name: front
    driver: bridge
    external: true

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8080:80
    networks:
      - front
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - 81:81
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
